### ISSUE TITLE
cupy.cuda.driver ERROR 

### ISSUE THREAD

**Issue by Vickeyhw** [chenyuntc/simple-faster-rcnn-pytorch#144]
when i try to train on voc dataset,i I have encountered errors below .why?Is it caused by wrong cupy version?  thanks 

Traceback (most recent call last):
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/train.py", line 133, in <module>
    train()
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/train.py", line 67, in train
    faster_rcnn = FasterRCNNVGG16()
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/model/faster_rcnn_vgg16.py", line 76, in __init__
    classifier=classifier
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/model/faster_rcnn_vgg16.py", line 115, in __init__
    self.roi = RoIPooling2D(self.roi_size, self.roi_size, self.spatial_scale)
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 81, in __init__
    self.RoI = RoI(outh, outw, spatial_scale)
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 30, in __init__
    self.forward_fn = load_kernel('roi_forward', kernel_forward)
  File "cupy/util.pyx", line 55, in cupy.util.memoize.decorator.ret
  File "/home/huangwei/PycharmProjects/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 18, in load_kernel
    kernel_code = cupy.cuda.compile_with_cache(code)
  File "/home/huangwei/anaconda3/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 167, in compile_with_cache
    ls.add_ptr_data(ptx, u'cupy.ptx')
  File "cupy/cuda/function.pyx", line 212, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/function.pyx", line 214, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/driver.pyx", line 153, in cupy.cuda.driver.linkAddData
  File "cupy/cuda/driver.pyx", line 82, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

**Comment by fanhaobeibei** [comment]
i meet the same problem

runfile('/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/train.py', args=['train', '--caffe-pretrain=True'], wdir='/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master')
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': './misc/checkpoints/vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'faster-rcnn',
 'epoch': 2,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 1,
 'plot_every': 0,
 'port': None,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 1,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/VOCdevkit/VOC2007',
 'weight_decay': 0.0005}
==========end============
load data
Traceback (most recent call last):
  File "/home/julyedu_481243/.conda/envs/pytorch-faster-rcnn/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-eeb2e4cda463>", line 1, in <module>
    runfile('/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/train.py', args=['train', '--caffe-pretrain=True'], wdir='/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master')
  File "/home/julyedu_481243/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/julyedu_481243/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/train.py", line 132, in <module>
    fire.Fire()
  File "/home/julyedu_481243/.conda/envs/pytorch-faster-rcnn/lib/python3.7/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/julyedu_481243/.conda/envs/pytorch-faster-rcnn/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/julyedu_481243/.conda/envs/pytorch-faster-rcnn/lib/python3.7/site-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/train.py", line 67, in train
    faster_rcnn = FasterRCNNVGG16()
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/model/faster_rcnn_vgg16.py", line 78, in __init__
    classifier=classifier
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/model/faster_rcnn_vgg16.py", line 117, in __init__
    self.roi = RoIPooling2D(self.roi_size, self.roi_size, self.spatial_scale)
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 82, in __init__
    self.RoI = RoI(outh, outw, spatial_scale)
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 31, in __init__
    self.forward_fn = load_kernel('roi_forward', kernel_forward)
  File "cupy/util.pyx", line 55, in cupy.util.memoize.decorator.ret
  File "/home/julyedu_481243/fan/simple-faster-rcnn-pytorch-master/model/roi_module.py", line 18, in load_kernel
    kernel_code = cupy.cuda.compile_with_cache(code)
  File "/home/julyedu_481243/.conda/envs/pytorch-faster-rcnn/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 167, in compile_with_cache
    ls.add_ptr_data(ptx, u'cupy.ptx')
  File "cupy/cuda/function.pyx", line 212, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/function.pyx", line 214, in cupy.cuda.function.LinkState.add_ptr_data
  File "cupy/cuda/driver.pyx", line 153, in cupy.cuda.driver.linkAddData
  File "cupy/cuda/driver.pyx", line 82, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

**Comment by fanhaobeibei** [comment]
my problem has solved :
cuda,cudatoolkit,cupy,torch,torchvision should match cuda version.
so,maybe you can check them : conda list   or  pip list

**Comment by youmu11** [comment]
> my problem has solved :
> cuda,cudatoolkit,cupy,torch,torchvision should match cuda version.
> so,maybe you can check them : conda list or pip list

so what's the relationship among them?

**Comment by fanhaobeibei** [comment]
> > my problem has solved :
> > cuda,cudatoolkit,cupy,torch,torchvision should match cuda version.
> > so,maybe you can check them : conda list or pip list
> 
> so what's the relationship among them?

they should have the same cuda version,but if you directly install ,you maybe get the wrong package.
i solved it by  :
firstly conda install cudatoolkit 9.0
then conda install cupy
